function anexoa(){
    document.getElementById("anexoA").style.display = "flex"
    document.getElementById("anexoB").style.display = "none"
    document.getElementById("anexoC").style.display = "none"
    document.getElementById("anexoD").style.display = "none"
    document.getElementById("anexoE").style.display = "none"
    document.getElementById("anexoF").style.display = "none"
    document.getElementById("anexoG").style.display = "none"
    document.getElementById("anexoH").style.display = "none"
    document.getElementById("anexoI").style.display = "none"
    document.getElementById("anexoJ").style.display = "none"
    document.getElementById("anexoK").style.display = "none"
}
function anexob(){
    document.getElementById("anexoA").style.display = "none"
    document.getElementById("anexoB").style.display = "flex"
    document.getElementById("anexoC").style.display = "none"
    document.getElementById("anexoD").style.display = "none"
    document.getElementById("anexoE").style.display = "none"
    document.getElementById("anexoF").style.display = "none"
    document.getElementById("anexoG").style.display = "none"
    document.getElementById("anexoH").style.display = "none"
    document.getElementById("anexoI").style.display = "none"
    document.getElementById("anexoJ").style.display = "none"
    document.getElementById("anexoK").style.display = "none"
}
function anexoc(){
    document.getElementById("anexoA").style.display = "none"
    document.getElementById("anexoB").style.display = "none"
    document.getElementById("anexoC").style.display = "flex"
    document.getElementById("anexoD").style.display = "none"
    document.getElementById("anexoE").style.display = "none"
    document.getElementById("anexoF").style.display = "none"
    document.getElementById("anexoG").style.display = "none"
    document.getElementById("anexoH").style.display = "none"
    document.getElementById("anexoI").style.display = "none"
    document.getElementById("anexoJ").style.display = "none"
    document.getElementById("anexoK").style.display = "none"
}
function anexod(){
    document.getElementById("anexoA").style.display = "none"
    document.getElementById("anexoB").style.display = "none"
    document.getElementById("anexoC").style.display = "none"
    document.getElementById("anexoD").style.display = "flex"
    document.getElementById("anexoE").style.display = "none"
    document.getElementById("anexoF").style.display = "none"
    document.getElementById("anexoG").style.display = "none"
    document.getElementById("anexoH").style.display = "none"
    document.getElementById("anexoI").style.display = "none"
    document.getElementById("anexoJ").style.display = "none"
    document.getElementById("anexoK").style.display = "none"
}
function anexoe(){
    document.getElementById("anexoA").style.display = "none"
    document.getElementById("anexoB").style.display = "none"
    document.getElementById("anexoC").style.display = "none"
    document.getElementById("anexoD").style.display = "none"
    document.getElementById("anexoE").style.display = "flex"
    document.getElementById("anexoF").style.display = "none"
    document.getElementById("anexoG").style.display = "none"
    document.getElementById("anexoH").style.display = "none"
    document.getElementById("anexoI").style.display = "none"
    document.getElementById("anexoJ").style.display = "none"
    document.getElementById("anexoK").style.display = "none"
}
function anexof(){
    document.getElementById("anexoA").style.display = "none"
    document.getElementById("anexoB").style.display = "none"
    document.getElementById("anexoC").style.display = "none"
    document.getElementById("anexoD").style.display = "none"
    document.getElementById("anexoE").style.display = "none"
    document.getElementById("anexoF").style.display = "flex"
    document.getElementById("anexoG").style.display = "none"
    document.getElementById("anexoH").style.display = "none"
    document.getElementById("anexoI").style.display = "none"
    document.getElementById("anexoJ").style.display = "none"
    document.getElementById("anexoK").style.display = "none"
}
function anexog(){
    document.getElementById("anexoA").style.display = "none"
    document.getElementById("anexoB").style.display = "none"
    document.getElementById("anexoC").style.display = "none"
    document.getElementById("anexoD").style.display = "none"
    document.getElementById("anexoE").style.display = "none"
    document.getElementById("anexoF").style.display = "none"
    document.getElementById("anexoG").style.display = "flex"
    document.getElementById("anexoH").style.display = "none"
    document.getElementById("anexoI").style.display = "none"
    document.getElementById("anexoJ").style.display = "none"
    document.getElementById("anexoK").style.display = "none"
}
function anexoh(){
    document.getElementById("anexoA").style.display = "none"
    document.getElementById("anexoB").style.display = "none"
    document.getElementById("anexoC").style.display = "none"
    document.getElementById("anexoD").style.display = "none"
    document.getElementById("anexoE").style.display = "none"
    document.getElementById("anexoF").style.display = "none"
    document.getElementById("anexoG").style.display = "none"
    document.getElementById("anexoH").style.display = "flex"
    document.getElementById("anexoI").style.display = "none"
    document.getElementById("anexoJ").style.display = "none"
    document.getElementById("anexoK").style.display = "none"
}
function anexoi(){
    document.getElementById("anexoA").style.display = "none"
    document.getElementById("anexoB").style.display = "none"
    document.getElementById("anexoC").style.display = "none"
    document.getElementById("anexoD").style.display = "none"
    document.getElementById("anexoE").style.display = "none"
    document.getElementById("anexoF").style.display = "none"
    document.getElementById("anexoG").style.display = "none"
    document.getElementById("anexoH").style.display = "none"
    document.getElementById("anexoI").style.display = "flex"
    document.getElementById("anexoJ").style.display = "none"
    document.getElementById("anexoK").style.display = "none"
}
function anexoj(){
    document.getElementById("anexoA").style.display = "none"
    document.getElementById("anexoB").style.display = "none"
    document.getElementById("anexoC").style.display = "none"
    document.getElementById("anexoD").style.display = "none"
    document.getElementById("anexoE").style.display = "none"
    document.getElementById("anexoF").style.display = "none"
    document.getElementById("anexoG").style.display = "none"
    document.getElementById("anexoH").style.display = "none"
    document.getElementById("anexoI").style.display = "none"
    document.getElementById("anexoJ").style.display = "flex"
    document.getElementById("anexoK").style.display = "none"
}
function anexok(){
    document.getElementById("anexoA").style.display = "none"
    document.getElementById("anexoB").style.display = "none"
    document.getElementById("anexoC").style.display = "none"
    document.getElementById("anexoD").style.display = "none"
    document.getElementById("anexoE").style.display = "none"
    document.getElementById("anexoF").style.display = "none"
    document.getElementById("anexoG").style.display = "none"
    document.getElementById("anexoH").style.display = "none"
    document.getElementById("anexoI").style.display = "none"
    document.getElementById("anexoJ").style.display = "none"
    document.getElementById("anexoK").style.display = "flex"
}